//Name Daniel Mesfin Abamecha 
//ID 1732/12
package labassignment;//this the package that is need for mmy working 
//Q#7: Write a Java program to create and display unique three-digit number using 1, 2, 3, 4. Also count how 
//many three-digit numbers are there. producing the unquie number using 1234

public class UnquieNumber {//here class diclration 
public static void main(String[] args) {//main mthod
    // we have mathematical concept that is used to produce unque number  and calculate the numbers of them which is called permution and combination 
    //that is p(4,3) is equals to 24 :-4! or 4*3*2*1=24 while we produce by combination with out  repitation.
    int amount = 0;//variable intialization to accumulate the amout of unqie number which is generated by the program
    for(int i = 1; i <= 4; i++){
	for(int j = 1; j <= 4; j++){
	    for(int k = 1; k <= 4; k++){
		if(k != i && k != j && i != j){
		    amount++;
		    System.out.print(i + "" + j + "" + k+" ,");
                }
            }
        }
        System.out.println("\n");// new line two times 
    }
    System.out.println("Total number of the three-digit-number is " + amount+"\n");
}
}
    
